{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: exemplo-cronjob
  annotations:
    link.argocd.argoproj.io/external-link: "https://shortly.cc/OZJIu"
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: {{ .Values.cronjob.image }}
              command: {{ toJson .Values.cronjob.command }}
          restartPolicy: Never
{{- end }}
