{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: exemplo-job
spec:
  template:
    spec:
      containers:
        - name: job
          image: {{ .Values.job.image }}
          command: {{ .Values.job.command }}
      restartPolicy: Never
  backoffLimit: 1
{{- end }}
